FROM elasticsearch:latest

RUN /usr/share/elasticsearch/bin/plugin install polyfractal/elasticsearch-inquisitor &&\
    /usr/share/elasticsearch/bin/plugin install elasticsearch/elasticsearch-mapper-attachments/2.6.0
