web:
    build: ./containers/web
    ports:
        - "3000:80"
    volumes:
        - ".:/app"
    environment:
        CREATE_MYSQL_BASIC_USER_AND_DB: "true"
        MYSQL_USER_NAME: kezaco
        MYSQL_USER_DB: kezaco
        MYSQL_USER_PASS: kezaco
        MYSQL_ADMIN_PASS: toor
    links:
        - elasticsearch
elasticsearch:
    build: ./containers/elasticsearch
    ports:
        - "9200:9200"
