# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    kezaco.twig.gravatar_extension:
        class: Kezaco\CoreBundle\Twig\GravatarExtension
        tags:
            - { name: twig.extension }
